import React, { useRef } from 'react';
import { ArrowLeft, Printer, Copy, CheckCircle2, XCircle } from 'lucide-react';
import { clsx } from 'clsx';
import { Button } from '@/components/ui/Button';
import { toast } from 'sonner';
import type { SurveyResponses } from '@/components/feedback/ConfidenceSurvey';
import type { BlockId } from '@/types/content';

interface StageResult {
  stage: number;
  title: string;
  score: number;
  total: number;
  percent: number;
  passed: boolean;
  pedagogicalGoal: string;
}

interface PrintableSummaryProps {
  blockId: BlockId;
  blockTitle: string;
  stageData: StageResult[];
  totalXP: number;
  overallPercent: number;
  timeTaken: string;
  takeaways: string[];
  preSurveyResponses: SurveyResponses | null;
  onBack: () => void;
}

const SURVEY_LABELS = [
  'Understanding financial records',
  'Reading financial statements',
  'Basics of investing',
  'Financial decision-making',
  'Technology in finance',
] as const;

export const PrintableSummary: React.FC<PrintableSummaryProps> = ({
  blockTitle,
  stageData,
  totalXP,
  overallPercent,
  timeTaken,
  takeaways,
  preSurveyResponses,
  onBack,
}) => {
  const contentRef = useRef<HTMLDivElement>(null);

  const handlePrint = () => {
    window.print();
  };

  const handleCopy = async () => {
    const lines: string[] = [];
    lines.push(`WorkReady Finance — ${blockTitle} Summary`);
    lines.push(`${'═'.repeat(50)}`);
    lines.push(`Date: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`);
    lines.push('');
    lines.push(`Overall Accuracy: ${overallPercent}%`);
    lines.push(`Total XP Earned: ${totalXP}`);
    lines.push(`Time Taken: ${timeTaken}`);
    lines.push('');
    lines.push('Stage Results');
    lines.push(`${'─'.repeat(50)}`);
    stageData.forEach((s) => {
      lines.push(`  Stage ${s.stage}: ${s.title} — ${s.score}/${s.total} (${s.percent}%) ${s.passed ? '✓' : '✗'}`);
    });
    if (takeaways.length > 0) {
      lines.push('');
      lines.push('Key Learning Takeaways');
      lines.push(`${'─'.repeat(50)}`);
      takeaways.forEach((t, i) => lines.push(`  ${i + 1}. ${t}`));
    }
    if (preSurveyResponses) {
      lines.push('');
      lines.push('Pre-Block Confidence Ratings (1-5)');
      lines.push(`${'─'.repeat(50)}`);
      SURVEY_LABELS.forEach((label, i) => {
        const key = `q${i + 1}` as keyof SurveyResponses;
        lines.push(`  ${label}: ${preSurveyResponses[key]}/5`);
      });
    }
    lines.push('');
    lines.push('— Generated by WorkReady Finance (UWE Bristol)');

    try {
      await navigator.clipboard.writeText(lines.join('\n'));
      toast.success('Summary copied to clipboard');
    } catch {
      toast.error('Failed to copy — try using Ctrl+C');
    }
  };

  const dateStr = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  return (
    <div className="print-summary min-h-screen bg-slate-50 print:bg-white">
      {/* Non-print toolbar */}
      <div className="no-print sticky top-0 z-10 bg-white border-b border-slate-200 px-4 py-3 flex items-center justify-between">
        <Button variant="ghost" size="sm" onClick={onBack}>
          <ArrowLeft className="w-4 h-4 mr-1" /> Back
        </Button>
        <div className="flex gap-2">
          <Button variant="secondary" size="sm" onClick={handleCopy}>
            <Copy className="w-4 h-4 mr-1" /> Copy
          </Button>
          <Button size="sm" onClick={handlePrint}>
            <Printer className="w-4 h-4 mr-1" /> Print
          </Button>
        </div>
      </div>

      {/* Printable content */}
      <div
        ref={contentRef}
        className="max-w-2xl mx-auto px-6 py-8 print:max-w-none print:px-12 print:py-8"
      >
        {/* Header */}
        <div className="mb-8 border-b-2 border-slate-900 pb-4">
          <h1 className="text-2xl font-extrabold text-slate-900">WorkReady Finance</h1>
          <p className="text-xs text-slate-500 mt-1">UWE Bristol — HEIF Financial Literacy Programme</p>
          <div className="mt-4 flex justify-between items-end">
            <div>
              <h2 className="text-lg font-bold text-slate-800">{blockTitle} — Session Summary</h2>
            </div>
            <p className="text-xs text-slate-400">{dateStr}</p>
          </div>
        </div>

        {/* Stats row */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          <StatBox label="Overall Accuracy" value={`${overallPercent}%`} />
          <StatBox label="Total XP" value={`${totalXP}`} />
          <StatBox label="Time Taken" value={timeTaken} />
        </div>

        {/* Stage results table */}
        <section className="mb-8">
          <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-3">Stage Results</h3>
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="border-b-2 border-slate-300 text-left">
                <th className="py-2 font-semibold text-slate-600">Stage</th>
                <th className="py-2 font-semibold text-slate-600">Title</th>
                <th className="py-2 font-semibold text-slate-600 text-center">Score</th>
                <th className="py-2 font-semibold text-slate-600 text-center">%</th>
                <th className="py-2 font-semibold text-slate-600 text-center">Pass</th>
              </tr>
            </thead>
            <tbody>
              {stageData.map((s) => (
                <tr key={s.stage} className="border-b border-slate-200">
                  <td className="py-2 font-bold text-slate-700">{s.stage}</td>
                  <td className="py-2 text-slate-700">{s.title}</td>
                  <td className="py-2 text-center text-slate-700">{s.score}/{s.total}</td>
                  <td className={clsx(
                    'py-2 text-center font-bold',
                    s.percent >= 80 ? 'text-emerald-600' : s.percent >= 60 ? 'text-amber-600' : 'text-red-500',
                  )}>
                    {s.percent}%
                  </td>
                  <td className="py-2 text-center">
                    {s.passed ? (
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 inline-block" />
                    ) : (
                      <XCircle className="w-4 h-4 text-red-400 inline-block" />
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* Key takeaways */}
        {takeaways.length > 0 && (
          <section className="mb-8">
            <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-3">Key Learning Takeaways</h3>
            <ul className="space-y-2">
              {takeaways.map((goal, i) => (
                <li key={i} className="text-sm text-slate-700 flex items-start gap-2">
                  <span className="text-emerald-600 font-bold shrink-0">{i + 1}.</span>
                  {goal}
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Confidence survey snapshot */}
        {preSurveyResponses && (
          <section className="mb-8">
            <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-3">Pre-Block Confidence Ratings</h3>
            <table className="w-full text-sm border-collapse">
              <thead>
                <tr className="border-b-2 border-slate-300 text-left">
                  <th className="py-2 font-semibold text-slate-600">Area</th>
                  <th className="py-2 font-semibold text-slate-600 text-center">Rating (1-5)</th>
                </tr>
              </thead>
              <tbody>
                {SURVEY_LABELS.map((label, i) => {
                  const key = `q${i + 1}` as keyof SurveyResponses;
                  const val = preSurveyResponses[key];
                  return (
                    <tr key={i} className="border-b border-slate-200">
                      <td className="py-2 text-slate-700">{label}</td>
                      <td className="py-2 text-center font-bold text-slate-900">{val}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </section>
        )}

        {/* What's next */}
        <section className="border-t-2 border-slate-900 pt-4 mt-8">
          <h3 className="text-sm font-bold text-slate-900 mb-2">What's Next?</h3>
          <p className="text-sm text-slate-600">
            Continue your financial literacy journey by exploring the remaining blocks in WorkReady Finance.
            Each block builds on your understanding with real-world workplace scenarios.
          </p>
        </section>

        {/* Footer */}
        <p className="text-xs text-slate-400 mt-8 text-center print:mt-12">
          WorkReady Finance © {new Date().getFullYear()} UWE Bristol — Generated on {dateStr}
        </p>
      </div>
    </div>
  );
};

// ── Stat box sub-component ────────────────────────────────────────────

const StatBox: React.FC<{ label: string; value: string }> = ({ label, value }) => (
  <div className="border border-slate-300 rounded-lg p-3 text-center print:border-slate-400">
    <p className="text-xl font-extrabold text-slate-900">{value}</p>
    <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider mt-1">{label}</p>
  </div>
);
